dist: trusty
language: python
python:
  - "3.5.1"
  - "3.5.2"
  - "3.5.4"
  - "3.6"
install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -U tox
script:
  - export TOXENV=py`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`
  - echo "$TOXENV"

  - tox
after_success:
  - pip install codecov
  - codecov
cache: pip
notifications:
  email: false
  slack: oceanio:qISToAOQglhPzOlbJ3CjNJLF
